# Generated by Django 5.2.8 on 2026-03-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100)),
                ('timestamp', models.IntegerField(help_text='Minute of the game')),
                ('event_type', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('player', models.CharField(blank=True, max_length=100, null=True)),
                ('possession_stat', models.FloatField(default=50.0)),
                ('x_coord', models.FloatField(blank=True, null=True)),
                ('y_coord', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
